[package]
name = "identity-grpc"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/identity.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "identity-grpc"
path = "src/main.rs"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.75"
tokio-stream = { version = "0.1.14", features = ["net"] }
identity_iota = { path = "../../identity_iota", features = ["resolver"] }
identity_storage = { path = "../../identity_storage", features = ["memstore"] }
iota-sdk = { version = "1.1.2", features = ["stronghold"] }
serde_json = { version = "1.0.108", features = ["alloc"] }
thiserror = "1.0.50"
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.10"
